language: emacs-lisp
jobs:
  include:
    - stage: deploy
      os: osx
      addons:
        homebrew:
          packages:
            - mingw-w64
          update: true
      deploy:
        provider: releases
        api_key:
          secure: fV9fQbw4kjVHAsxvZO9xpvShPRqYSKTvk5rKrohqPoj0re0UmPXFJB+0wgZskZPrE3bgjbWJAmz2+/P4Y70kWUtQgswhITzZSoRyXO9SKutPBBZ53QeWuMhUUqstxIYGs5Oo3g/SM++RnzHk1mkQ7+0nHq1bhH48Ow+gYDzv2d0tA0GCyrLlY15XQtAM7HYRq7qZpFBOsVXbFe4kCdgL2p1BjplaMMX0JCbmKRpk8Jwdoi6Xk67be7pAOskK64aFm4bGySL4UwVzgHChoNEonIsh/fKVsosPnhKXLa47zlmjk0TA39AccZ+Rfu97a6fj1CqlGPEK4mvyRKaBGk6DiSINEbmJsA1RmX6mxTNhE/P7/rvPZDnJFGAxicJv175dnQ5BpvpP/ZONsgVV3TUDpCT6iSmOG2VaMwWfak43x2Ps3rptfCzT3Vz6uoAX5bGSQQ32e0q9gQpLstNwigG1ntcPCcVSoZGyAjC1gQdIA2KUepNFlYv/7CHUF4TmXT3ljL2nZmE2I74WUby9dEpyNeJZfHsZe9a9SpjcByp4rRaiMS65WKOTbOOy5xDc3kMBqt0ZlqI7hDb3BVEuFHeR1Fk4haoR+fv1tviMF9ye3rA+eaOpj13dmHiaI4laJ9bRJp0fCslDOz7H5gMvL3Ebow1Y/PLkcnuN/e3EBZmEY+U=
        file_glob: true
        file: products/*
        skip_cleanup: true
        overwrite: true
        on:
          all_branches: true
      env:
        - ZMQ_BUILD_HOST=x86_64-w64-mingw32
      script:
        - cd $TRAVIS_BUILD_DIR
        - make products
