language: emacs-lisp
dist: trusty
# https://github.com/travis-ci/travis-ci/issues/9061
sudo: required
matrix:
  allow_failures:
    - env: EMACS_VERSION=git-snapshot
env:
  - EMACS_VERSION=26-pretest
  - EMACS_VERSION=git-snapshot
before_install:
  # Setup paths
  - export PATH=${TRAVIS_BUILD_DIR}/.evm/bin:${PATH}
  # Install emacs
  - if [[ ${EMACS_VERSION} = git-snapshot ]]; then sudo apt-get install -y texinfo; fi
  # Use this fork of EVM for dynamic module support
  - git clone https://github.com/ubolonton/evm ${TRAVIS_BUILD_DIR}/.evm
  - evm config path /tmp
  - evm install emacs-${EMACS_VERSION} --use --skip
script:
  - cd $TRAVIS_BUILD_DIR
  - make
  - make test
