environment:
  PATH:  C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%
  ZMQ_BUILD_HOST: x86_64-w64-mingw32
artifacts:
  - path: products\*
deploy:
  provider: GitHub
  auth_token:
    secure: wIcRCyjAXLJs2OjhKgliY0PGC3WxTRXdkwmEYR1gzaCTji8BR7pL5jbP0rFxuC/P
  artifact: /.*\.tar\.gz(\.sha256)?/
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
cache:
  - C:\msys64\var\cache\pacman\pkg
  - C:\projects\emacs-zmq\src\libzmq
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - pacman --needed --noconfirm -Syu
  - pacman --needed --noconfirm -Sy
  - pacman --needed --noconfirm -S mingw-w64-x86_64-emacs
build_script:
  - make
  - if %APPVEYOR_REPO_TAG% == true ( make products )
test_script:
  - mkdir tmp
  - cp zmq.el zmq-tests.el %ZMQ_BUILD_HOST%/emacs-zmq.dll Makefile tmp
  - cd tmp
  - make test
